// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: colour.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CurrentColour struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Colour string `protobuf:"bytes,1,opt,name=colour,proto3" json:"colour,omitempty"`
}

func (x *CurrentColour) Reset() {
	*x = CurrentColour{}
	if protoimpl.UnsafeEnabled {
		mi := &file_colour_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrentColour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentColour) ProtoMessage() {}

func (x *CurrentColour) ProtoReflect() protoreflect.Message {
	mi := &file_colour_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentColour.ProtoReflect.Descriptor instead.
func (*CurrentColour) Descriptor() ([]byte, []int) {
	return file_colour_proto_rawDescGZIP(), []int{0}
}

func (x *CurrentColour) GetColour() string {
	if x != nil {
		return x.Colour
	}
	return ""
}

type NewColour struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Colour string `protobuf:"bytes,1,opt,name=colour,proto3" json:"colour,omitempty"`
}

func (x *NewColour) Reset() {
	*x = NewColour{}
	if protoimpl.UnsafeEnabled {
		mi := &file_colour_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewColour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewColour) ProtoMessage() {}

func (x *NewColour) ProtoReflect() protoreflect.Message {
	mi := &file_colour_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewColour.ProtoReflect.Descriptor instead.
func (*NewColour) Descriptor() ([]byte, []int) {
	return file_colour_proto_rawDescGZIP(), []int{1}
}

func (x *NewColour) GetColour() string {
	if x != nil {
		return x.Colour
	}
	return ""
}

var File_colour_proto protoreflect.FileDescriptor

var file_colour_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27,
	0x0a, 0x0d, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x22, 0x23, 0x0a, 0x09, 0x4e, 0x65, 0x77, 0x43, 0x6f,
	0x6c, 0x6f, 0x75, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x32, 0x40, 0x0a, 0x0f,
	0x43, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12,
	0x2d, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x43, 0x6f, 0x6c, 0x6f, 0x75, 0x72,
	0x12, 0x0e, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x75, 0x72,
	0x1a, 0x0a, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x22, 0x00, 0x42, 0x08,
	0x5a, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_colour_proto_rawDescOnce sync.Once
	file_colour_proto_rawDescData = file_colour_proto_rawDesc
)

func file_colour_proto_rawDescGZIP() []byte {
	file_colour_proto_rawDescOnce.Do(func() {
		file_colour_proto_rawDescData = protoimpl.X.CompressGZIP(file_colour_proto_rawDescData)
	})
	return file_colour_proto_rawDescData
}

var file_colour_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_colour_proto_goTypes = []interface{}{
	(*CurrentColour)(nil), // 0: CurrentColour
	(*NewColour)(nil),     // 1: NewColour
}
var file_colour_proto_depIdxs = []int32{
	0, // 0: ColourGenerator.GetRandColour:input_type -> CurrentColour
	1, // 1: ColourGenerator.GetRandColour:output_type -> NewColour
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_colour_proto_init() }
func file_colour_proto_init() {
	if File_colour_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_colour_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrentColour); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_colour_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewColour); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_colour_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_colour_proto_goTypes,
		DependencyIndexes: file_colour_proto_depIdxs,
		MessageInfos:      file_colour_proto_msgTypes,
	}.Build()
	File_colour_proto = out.File
	file_colour_proto_rawDesc = nil
	file_colour_proto_goTypes = nil
	file_colour_proto_depIdxs = nil
}
